/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Entite.Admin;
import Entite.Classe;
import Entite.Etudiant;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import search.SearchClasse;
import search.SearchEtudiant;

/**
 *
 * @author seck
 */
public class Acceuil_Etudiant extends javax.swing.JFrame {

    SearchClasse sc = new SearchClasse();
    SearchEtudiant se = new SearchEtudiant(); 
    ArrayList<Etudiant> listEt;
    Admin admin = new Admin();
    Acceuil_surveillant AC =new Acceuil_surveillant();
    
    
    /**
     * Creates new form acceuil
     */
    public Acceuil_Etudiant() {
        initComponents();
        jTable1.getTableHeader().setFont(new Font("Segeo UI", Font.BOLD, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32,136,203));
        jTable1.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable1.setRowHeight(25);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_etudiant8 = new javax.swing.JButton();
        jButton_prof4 = new javax.swing.JButton();
        jButton_etudiant9 = new javax.swing.JButton();
        jButton_etudiant10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel_telephone = new javax.swing.JLabel();
        jTextField_telephone = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jLabel_numeroCarte = new javax.swing.JLabel();
        jTextField_numerCarte = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel_dateNaissance = new javax.swing.JLabel();
        jLabel_sexe = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField_prenom = new javax.swing.JTextField();
        jLabel_prenom = new javax.swing.JLabel();
        jLabel_nom = new javax.swing.JLabel();
        jTextField_nom = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton_nouveau = new javax.swing.JButton();
        jButton_modifier = new javax.swing.JButton();
        jButton_Supprimer = new javax.swing.JButton();
        jComboBox_chooseClasse = new javax.swing.JComboBox();
        jButton_chercher = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des émargements");
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 51, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 5, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSMISSION DE DONNEES ET SECURITE DE L'INFORMATION");

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTION DES ETUDIANTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(367, 367, 367))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 5, new java.awt.Color(0, 0, 0)));

        jButton_etudiant8.setBackground(new java.awt.Color(51, 51, 255));
        jButton_etudiant8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_etudiant8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/multiple-users-silhouette.png"))); // NOI18N
        jButton_etudiant8.setText("ETUDIANTS");
        jButton_etudiant8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 0, 153)));
        jButton_etudiant8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_etudiant8jButton_etudiantActionPerformed(evt);
            }
        });

        jButton_prof4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_prof4.setForeground(new java.awt.Color(1, 1, 1));
        jButton_prof4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/black-user-shape.png"))); // NOI18N
        jButton_prof4.setText("PROFESSEURS");
        jButton_prof4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(153, 0, 0)));
        jButton_prof4.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton_prof4.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton_prof4.setPreferredSize(new java.awt.Dimension(85, 23));
        jButton_prof4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_prof4jButton_profActionPerformed(evt);
            }
        });

        jButton_etudiant9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_etudiant9.setForeground(new java.awt.Color(1, 1, 1));
        jButton_etudiant9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/user.png"))); // NOI18N
        jButton_etudiant9.setText("UTILISATEURS");
        jButton_etudiant9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 102, 102)));
        jButton_etudiant9.setMaximumSize(new java.awt.Dimension(93, 23));
        jButton_etudiant9.setMinimumSize(new java.awt.Dimension(93, 23));
        jButton_etudiant9.setPreferredSize(new java.awt.Dimension(93, 23));
        jButton_etudiant9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_etudiant9ActionPerformed(evt);
            }
        });

        jButton_etudiant10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_etudiant10.setForeground(new java.awt.Color(1, 1, 1));
        jButton_etudiant10.setText("LISTE DE PRESENCE");
        jButton_etudiant10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(153, 0, 153)));
        jButton_etudiant10.setMaximumSize(new java.awt.Dimension(93, 23));
        jButton_etudiant10.setMinimumSize(new java.awt.Dimension(93, 23));
        jButton_etudiant10.setPreferredSize(new java.awt.Dimension(93, 23));
        jButton_etudiant10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_etudiant10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_prof4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_etudiant9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_etudiant10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_etudiant8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton_etudiant8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton_prof4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton_etudiant9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton_etudiant10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro Carte", "Nom", "Prénom", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(0, 51, 204));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 5, new java.awt.Color(0, 0, 0)));

        jLabel_telephone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_telephone.setText("Telephone");

        jTextField_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telephoneActionPerformed(evt);
            }
        });

        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });

        jLabel_email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_email.setText("Email");

        jLabel_numeroCarte.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_numeroCarte.setText("Numero carte");

        jLabel_dateNaissance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_dateNaissance.setText("Date naissance");

        jLabel_sexe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_sexe.setText("Sexe");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel_prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_prenom.setText("Prenom");

        jLabel_nom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_nom.setText("Nom");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_telephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_numeroCarte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_dateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_sexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_nom)
                    .addComponent(jTextField_prenom)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_numerCarte)
                    .addComponent(jTextField_email)
                    .addComponent(jTextField_telephone))
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_prenom))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sexe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_dateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numeroCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_numerCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 5, new java.awt.Color(0, 0, 0)));

        jButton_nouveau.setBackground(new java.awt.Color(255, 255, 255));
        jButton_nouveau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_nouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/file.png"))); // NOI18N
        jButton_nouveau.setText("Nouveau");
        jButton_nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nouveauActionPerformed(evt);
            }
        });

        jButton_modifier.setBackground(new java.awt.Color(255, 255, 255));
        jButton_modifier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/file (2).png"))); // NOI18N
        jButton_modifier.setText("Modifier");
        jButton_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifierActionPerformed(evt);
            }
        });

        jButton_Supprimer.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Supprimer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/file (1).png"))); // NOI18N
        jButton_Supprimer.setText("Supprimer");
        jButton_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton_Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox_chooseClasse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_chooseClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "L1TDSI", "L2TDSI", "L3TDSI" }));
        jComboBox_chooseClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_chooseClasseActionPerformed(evt);
            }
        });

        jButton_chercher.setBackground(new java.awt.Color(255, 255, 255));
        jButton_chercher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_chercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/search.png"))); // NOI18N
        jButton_chercher.setText("Recherche");
        jButton_chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chercherActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Capt1.PNG"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/as.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(jComboBox_chooseClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton_chercher, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(347, 347, 347)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_chooseClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_chercher))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1410, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_etudiant8jButton_etudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_etudiant8jButton_etudiantActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_jButton_etudiant8jButton_etudiantActionPerformed

    private void jButton_prof4jButton_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_prof4jButton_profActionPerformed
        // TODO add your handling code here:
        Acceuil_Prof AP =new Acceuil_Prof();
        AP.setVisible(true);
    }//GEN-LAST:event_jButton_prof4jButton_profActionPerformed

    private void jTextField_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telephoneActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jComboBox_chooseClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_chooseClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_chooseClasseActionPerformed

    private void jButton_chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chercherActionPerformed
        // TODO add your handling code here:
        String classe = jComboBox_chooseClasse.getSelectedItem().toString();
        ArrayList<Classe> listCl  = sc.RechercherParNomClasse(classe);
        try {
           // listEt = se.RechercherParClasse(listCl.get(0));
        } catch (Exception e) {
        }
        
        removeRowToTable();
        addRowToTable();
        
        
         
    }//GEN-LAST:event_jButton_chercherActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String classe1 = jComboBox_chooseClasse.getSelectedItem().toString();
         ArrayList<Classe> listC2  = sc.RechercherParNomClasse(classe1);
         int i = jTable1.getSelectedRow();
        ArrayList<Etudiant> lis= se.RechercherParClasse(jComboBox_chooseClasse.getSelectedItem().toString());
        jTextField_nom.setText(lis.get(i).getNom());
        jTextField_prenom.setText(lis.get(i).getPrenom());
        jComboBox1.setSelectedItem(lis.get(i).getSexe());
        dateChooserCombo1.setText(lis.get(i).getDateNaissance());
        jTextField_numerCarte.setText(lis.get(i).getNumeroCarte());
        jTextField_email.setText(lis.get(i).getEmailEtudiant());
        jTextField_telephone.setText(lis.get(i).getTelEtudiant());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_etudiant9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_etudiant9ActionPerformed
        // TODO add your handling code here:
        Acceuil_user Au = new Acceuil_user();
        this.setVisible(false);
        Au.setVisible(true);
    }//GEN-LAST:event_jButton_etudiant9ActionPerformed

    private void jButton_etudiant10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_etudiant10ActionPerformed
        // TODO add your handling code here:
        Acceuil_Liste_presence alp = new Acceuil_Liste_presence();
        this.setVisible(false);
        alp.setVisible(true);
    }//GEN-LAST:event_jButton_etudiant10ActionPerformed

    private void jButton_nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nouveauActionPerformed
        // TODO add your handling code here:
        formulaireEtudiant formulaireEt = new formulaireEtudiant();
        formulaireEt.setVisible(true);
        removeRowToTable();
        addRowToTable();
    }//GEN-LAST:event_jButton_nouveauActionPerformed

    private void jButton_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifierActionPerformed
        // TODO add your handling code here:
       String classe1 = jComboBox_chooseClasse.getSelectedItem().toString();
        int i = jTable1.getSelectedRow();
        TableModel tablemodel = jTable1.getModel();
        ArrayList<Etudiant> lis= se.RechercherParClasse(classe1);
        int id_etudiant = lis.get(i).getIdEtudiant();
        String nom_etudiant = jTextField_nom.getText();
        String prenom_etudiant = jTextField_prenom.getText();
        String sexe_etudiant = jComboBox1.getSelectedItem().toString();
        String date_naissance =  dateChooserCombo1.getText();
        String numeroCarte = jTextField_numerCarte.getText();
        String email_etudiant = jTextField_email.getText();
        String tel_etudiant = jTextField_telephone.getText();
        Etudiant Et = new Etudiant(id_etudiant,nom_etudiant,prenom_etudiant,email_etudiant,tel_etudiant,sexe_etudiant,numeroCarte,date_naissance);
        admin.ModifierEtudiant(Et);
        JOptionPane.showMessageDialog(null, "Modification réussie");
        removeRowToTable();
        addRowToTable();
    }//GEN-LAST:event_jButton_modifierActionPerformed

    private void jButton_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupprimerActionPerformed
        // TODO add your handling code here:
        String classe1 = jComboBox_chooseClasse.getSelectedItem().toString();
        ArrayList<Classe> listC2  = sc.RechercherParNomClasse(classe1);
        int i = jTable1.getSelectedRow();
        TableModel tablemodel = jTable1.getModel();
        ArrayList<Etudiant> lis= se.RechercherParClasse(jComboBox_chooseClasse.getSelectedItem().toString());
        int id_etudiant = lis.get(i).getIdEtudiant();
        String nom_etudiant = jTextField_nom.getText();
        String prenom_etudiant = jTextField_prenom.getText();
        String sexe_etudiant = jComboBox1.getSelectedItem().toString();
        String date_naissance =  dateChooserCombo1.getText();
        String numeroCarte = jTextField_numerCarte.getText();
        String email_etudiant = jTextField_email.getText();
        String tel_etudiant = jTextField_telephone.getText();
        Etudiant Et = new Etudiant(id_etudiant,nom_etudiant,prenom_etudiant,email_etudiant,tel_etudiant,sexe_etudiant,numeroCarte,date_naissance);
        admin.SupprimerEtudiant(Et);
        JOptionPane.showMessageDialog(null, "Suppression réussie");
        removeRowToTable();
        addRowToTable();
    }//GEN-LAST:event_jButton_SupprimerActionPerformed

    public void removeRowToTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rows = model.getRowCount();
        for(int i = rows - 1; i >=0; i--)
        {
            model.removeRow(i); 
        }
       
    }
     public void addRowToTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<Etudiant> list = se.RechercherParClasse(jComboBox_chooseClasse.getSelectedItem().toString());
        Object rowData[] = new Object[4];
        
         if (list.size()== 0) {
             //JOptionPane.showMessageDialog(null, "aucun etudiant trouvé");
         }else{
        for (int i = 0; i < list.size(); i++) {                       
            rowData[0] = list.get(i).getNumeroCarte();
            rowData[1] = list.get(i).getNom();
            rowData[2] = list.get(i).getPrenom();
            rowData[3] = list.get(i).getEmailEtudiant();
            model.addRow(rowData);
        }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil_Etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton_Supprimer;
    private javax.swing.JButton jButton_chercher;
    private javax.swing.JButton jButton_etudiant10;
    private javax.swing.JButton jButton_etudiant8;
    private javax.swing.JButton jButton_etudiant9;
    private javax.swing.JButton jButton_modifier;
    private javax.swing.JButton jButton_nouveau;
    private javax.swing.JButton jButton_prof4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox jComboBox_chooseClasse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_dateNaissance;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_nom;
    private javax.swing.JLabel jLabel_numeroCarte;
    private javax.swing.JLabel jLabel_prenom;
    private javax.swing.JLabel jLabel_sexe;
    private javax.swing.JLabel jLabel_telephone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_numerCarte;
    private javax.swing.JTextField jTextField_prenom;
    private javax.swing.JTextField jTextField_telephone;
    // End of variables declaration//GEN-END:variables
}
